WebAppForWebshop/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data.Odbc;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Security.Claims;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using WebAppForWebshop.Data;
using WebAppForWebshop.Models;



namespace WebAppForWebshop.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _db;
        private UserManager<ApplicationUser> userManager;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public OrderController(ApplicationDbContext db, UserManager<ApplicationUser> userMrg, IHttpContextAccessor httpContextAccessor)
        {
            this._db = db;
            userManager = userMrg;
            this._httpContextAccessor = httpContextAccessor;
        }
        public IActionResult Index()
        {
            return View();
        }



        public IActionResult Checkout(string _CartId)
        {
            CartAndProduct model = new CartAndProduct();
            model.listForCartAndProduct = (from cart in _db.ShoppingCartItems
                                           join product in _db.Products on cart.ProductId equals product.Id
                                           into Details
                                           from m in Details.DefaultIfEmpty()
                                           select new CartAndProduct
                                           {
                                               CartId = _CartId,
                                               ProductId = m.Id,
                                               ProductName = m.Name,
                                               ProductImage = m.ProductImage,
                                               PricePerItem = m.Price,
                                               Quantity = cart.Quantity,
                                               TotalPrice = m.Price * cart.Quantity,
                                               DateCreated = cart.DateCreated,
                                               ItemId = cart.ItemId
                                           }).ToList();
            return View(model.listForCartAndProduct);
        }

        public void EmptyCart(string _CartId)
        {
            string ShoppingCartId = _CartId;
            var cartItems = _db.ShoppingCartItems.Where(
                c => c.CartId == ShoppingCartId);
            foreach (var cartItem in cartItems)
            {
                _db.ShoppingCartItems.Remove(cartItem);
            }
            // Save changes.             
            _db.SaveChanges();
        }

        public async Task<IActionResult> Receipt(string _CartId)
        {
            string removeCart = _CartId;
            CartAndProduct model = new CartAndProduct();
            // var user = await userManager.FindByIdAsync(User.Identity.GetType());
            var user = await userManager.GetUserAsync(HttpContext.User);
            var user1 = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            model.listForCartAndProduct = (from cart in _db.ShoppingCartItems
                                           join product in _db.Products on cart.ProductId equals product.Id
                                           into Details
                                           from m in Details.DefaultIfEmpty()
                                           select new CartAndProduct
                                           {
                                               CartId = _CartId,
                                               ProductId = m.Id,
                                               ProductName = m.Name,
                                               ProductImage = m.ProductImage,
                                               PricePerItem = m.Price,
                                               Quantity = cart.Quantity,
                                               TotalPrice = m.Price * cart.Quantity,
                                               DateCreated = cart.DateCreated,
                                               ItemId = cart.ItemId
                                           }).ToList();
            var insUser = (ApplicationUser)_db.Users.Where(x => x.Id == user1).FirstOrDefault();

            var order = new Orders()
            {
                OrderDate = DateTime.Now,
                Customer = insUser
            };
            await _db.Orders.AddAsync(order);
            await _db.SaveChangesAsync();
            var orderid = order.Id;
            foreach (var item in model.listForCartAndProduct)
            {
                int count = item.Quantity;
                while (count > 0)
                {
                    count--;
                    var orderref = new OrderReference()
                    {
                        OrderId = order,
                        ProductId = _db.Products.Where(p => p.Id == item.ProductId).FirstOrDefault(),
                        Price = item.PricePerItem
                    };
                    await _db.OrderReferences.AddAsync(orderref);
                }
            }
            EmptyCart(removeCart);
            await _db.SaveChangesAsync();

            return View(model.listForCartAndProduct);
        }

        
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> OrderHistory()
        {
            OrderHistory model = new OrderHistory();
            ApplicationUser tempUser = new ApplicationUser();
            model.listOrderHistory = (from oref in _db.OrderReferences
                                      join order in _db.Orders on oref.OrderId.Id
                                      equals order.Id
                                      join user in _db.Users on order.Customer.Id equals user.Id
                                      into Details
                                      from m in Details.DefaultIfEmpty()
                                      select new OrderHistory
                                      {
                                          OrderId = oref.OrderId.Id,
                                          CustomerId = m.Id,
                                          CustomerUsername = m.UserName,
                                          OrderDate = order.OrderDate,
                                          TotalPrice = oref.Price
                                      }).ToList();

            foreach (var item in model.listOrderHistory)
            {
                var user1 = (ApplicationUser)await _db.Users.Where(x => x.Id == item.CustomerId).FirstOrDefaultAsync();
                item.DeliveryAddress = user1.Address;

            }

            var tempo = new OrderHistory();

            foreach (var item in model.listOrderHistory)
            {
                tempo = new OrderHistory()
                {
                    OrderId = item.OrderId,
                    OrderDate = item.OrderDate,
                    CustomerId = item.CustomerId,
                    CustomerUsername = item.CustomerUsername,
                    DeliveryAddress = item.DeliveryAddress,
                    TotalPrice = item.TotalPrice
                };

                break;

            }

            //var temp = new OrderHistory();
            //var temp = model.listOrderHistory.FirstOrDefault();
            tempo.TotalPrice = tempo.TotalPrice - tempo.TotalPrice;
            foreach (var item in model.listOrderHistory)
            {

                if (tempo.OrderId != item.OrderId)
                {

                    model.finalHistoryList.Add(tempo);
                    tempo = new OrderHistory()
                    {
                        OrderId = item.OrderId,
                        OrderDate = item.OrderDate,
                        CustomerId = item.CustomerId,
                        CustomerUsername = item.CustomerUsername,
                        DeliveryAddress = item.DeliveryAddress,
                        TotalPrice = item.TotalPrice
                    };
                }
                else
                {

                    tempo.TotalPrice = tempo.TotalPrice + item.TotalPrice;
                }

            }
            model.finalHistoryList.Add(tempo);

            return View("OrderHistory", model);
        }

        public async Task<IActionResult> ManageOrder(int id)
        {
            SpecificOrderHistory model = new SpecificOrderHistory();
            model.listSpecificOrderHistory = (from prod in _db.Products
                                              join
                    oref in _db.OrderReferences on prod.Id equals oref.ProductId.Id
                                              join order in _db.Orders on oref.OrderId.Id
                                              equals order.Id
                                              join user in _db.Users on order.Customer.Id equals user.Id
                                              into Details
                                              from m in Details.DefaultIfEmpty()
                                              where oref.OrderId.Id == id
                                              select new SpecificOrderHistory
                                              {
                                                  OrderId = oref.OrderId.Id,
                                                  CustomerId = m.Id,
                                                  CustomerUsername = m.UserName,
                                                  OrderDate = order.OrderDate,

WebAppForWebshop/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebAppForWebshop.Data;
using WebAppForWebshop.Models;

namespace WebAppForWebshop.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {

        private RoleManager<IdentityRole> roleManager;
        private UserManager<ApplicationUser> userManager;

        private readonly ApplicationDbContext db;



        

        public RoleController(RoleManager<IdentityRole> roleMgr, UserManager<ApplicationUser> userMrg, ApplicationDbContext db)
        {
            roleManager = roleMgr;
            userManager = userMrg;
            this.db = db;
        }

        [Authorize(Roles ="Admin")]
        public ViewResult Index() => View(roleManager.Roles);
        [Authorize]
        public IActionResult Create() => View();

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create([Required] string name)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    Errors(result);
            }
            return View(name);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await roleManager.DeleteAsync(role);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    Errors(result);
            }
            else
                ModelState.AddModelError("", "No role found");
            return View("Index", roleManager.Roles);
        }

       
        [Authorize]
        public async Task<IActionResult> Update(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            List<ApplicationUser> members = new List<ApplicationUser>();
            List<ApplicationUser> nonMembers = new List<ApplicationUser>();
            foreach (ApplicationUser user in userManager.Users)
            {
                var list = await userManager.IsInRoleAsync(user, role.Name) ? members : nonMembers;
                list.Add(user);
            }
            return View(new RoleEdit
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Update(RoleModification model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.AddIds ?? new string[] { })
                {
                    ApplicationUser user = await userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await userManager.AddToRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                            Errors(result);
                    }
                }
                foreach (string userId in model.DeleteIds ?? new string[] { })
                {
                    ApplicationUser user = await userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await userManager.RemoveFromRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                            Errors(result);
                    }
                }
            }

            if (ModelState.IsValid)
                return RedirectToAction(nameof(Index));
            else
                return await Update(model.RoleId);
        }

        private void Errors(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
                ModelState.AddModelError("", error.Description);
        }
    }
}

WebAppForWebshop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Group 2 Project</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <title>Group2</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Main Stylesheet -->

    <link rel="stylesheet" href="~/themes/css/style.css">
    <link rel="stylesheet" href="~/themes/css/bootstrap.min.css">
    <link href="~/css/Custom.css" rel="stylesheet" />

</head>

<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand" asp-controller="Home" asp-action="Index"> <img class="media-object" src="~/images/Logo.png" alt="image" /></a>

            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    @*<li class="active">*@
                    <li>
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                    </li>

                    @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="Views" asp-page="/Products/Index">Products</a>
        </li>*@
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Products" asp-action="Index">Products</a>
                    </li>

                    <li class="dropdown dropdown-slide">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="350" role="button" aria-haspopup="true" aria-expanded="false">User <span class="tf-ion-ios-arrow-down"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="Home" asp-action="User">User</a></li>
                          @if (User.IsInRole("Admin"))
                          {  <li> <a asp-controller="Order" asp-action="OrderHistory">Orders History</a></li>}

                          


                        </ul>
                    </li>

                   
                   
                    <li><a asp-controller="Order"asp-action="ShoppingHistory" >Shopping History</a></li>
                </ul>
                


                

                <ul class="nav navbar-nav navbar-right">
                    @*<li><a href="#"><partial name="_LoginPartial" /></a></li>*@


                    <li class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        
                        <ul class="nav navbar-nav">
                            <li class=" nav-item">
                                <partial name="_LoginPartial" />
                                </li>
                                @if (User.IsInRole("Admin"))
                                {
                                <li class=" nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Create">Create Role</a>
                                </li>

                                <li class=" nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role Overview</a>
                                </li>

                            }

                            </ul>
                    </li>


                    <li class="nav-item">

                        <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCart" asp-action="Index"> <img class="media-object" src="~/images/cart.png" alt="image" /></a>

                    </li>
                </ul>




            </div>
        </div>
    </nav>



    <div class="jumbotron">
        <img class="media-object" src="~/images/banner.jpg" alt="image" />
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>



    <footer class="footer section text-center">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="social-media">
                        <li>
                            <a href="">
                                <i class="tf-ion-social-facebook"></i>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <i class="tf-ion-social-instagram"></i>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <i class="tf-ion-social-twitter"></i>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <i class="tf-ion-social-pinterest"></i>
                            </a>
                        </li>
                    </ul>
                    <ul class="footer-menu">
                        <li>
                            <a href="">CONTACT</a>
                        </li>
                        <li>
                            <a href="">SHIPPING</a>
                        </li>
                        <li>
                            <a href="">TERMS OF SERVICE</a>
                        </li>
                        <li>
                            <a href="">PRIVACY POLICY</a>
                        </li>
                    </ul>
                    <p-custom class="copyright-text">Powered by Group 2</p-custom>
                </div>
            </div>
        </div>
    </footer>
    <!--
    Essential Scripts
    =====================================-->
    <!-- Main jQuery -->
    <script src="~/themes/plugins/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.1 -->
    <script src="~/themes/plugins/bootstrap/js/bootstrap.min.js"></script>
    <!-- Bootstrap Touchpin -->
    <script src="~/themes/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js"></script>
    <!-- Instagram Feed Js -->
    <script src="~/themes/plugins/instafeed-js/instafeed.min.js"></script>
    <!-- Video Lightbox Plugin -->
    <script src="~/themes/plugins/ekko-lightbox/dist/ekko-lightbox.min.js"></script>
    <!-- Count Down Js -->
    <script src="~/themes/plugins/SyoTimer/build/jquery.syotimer.min.js"></script>
    <!-- Revolution Slider -->
    <script type="text/javascript" src="~/themes/plugins/revolution-slider/revolution/js/jquery.themepunch.tools.min.js"></script>
    <script type="text/javascript" src="~/themes/plugins/revolution-slider/revolution/js/jquery.themepunch.revolution.min.js"></script>
    <!-- Revolution Slider -->
    <script type="text/javascript" src="~/themes/plugins/revolution-slider/revolution/js/extensions/revolution.extension.actions.min.js"></script>
    <script type="text/javascript" src="~/themes/plugins/revolution-slider/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
    <script type="text/javascript" src="~/themes/plugins/revolution-slider/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
    <script type="text/javascript" src="~/themes/plugins/revolution-slider/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
    <script type="text/javascript" src="~/themes/plugins/revolution-slider/revolution/js/extensions/revolution.extension.migration.min.js"></script>
    <script type="text/javascript" src="~/themes/plugins/revolution-slider/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
    <script type="text/javascript" src="~/themes/plugins/revolution-slider/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
    <script type="text/javascript" src="~/themes/plugins/revolution-slider/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
    <script type="text/javascript" src="~/themes/plugins/revolution-slider/revolution/js/extensions/revolution.extension.video.min.js"></script>
    <script type="text/javascript" src="~/themes/plugins/revolution-slider/revolution/js/extensions/revolution.extension.video.min.js"></script>
    <script type="text/javascript" src="~/themes/plugins/revolution-slider/assets/warning.js"></script>

    <!-- Google Mapl -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCC72vZw-6tGqFyRhhg5CkF2fqfILn2Tsw"></script>
    <script type="text/javascript" src="~/themes/plugins/google-map/gmap.js"></script>
    <!-- Main Js File -->
    <script src="~/themes/js/script.js"></script>




    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>