WebAppForWebshop/Models/OrderHistory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppForWebshop.Models
{
    public class OrderHistory
    {
        public List<OrderHistory> listOrderHistory = new List<OrderHistory>();
        public List<OrderHistory> finalHistoryList = new List<OrderHistory>();
        public int OrderId { get; set; }

        public string CustomerId { get; set; }

        public string CustomerUsername { get; set; } //email or username of customer
        public string DeliveryAddress { get; set; }
        
        public DateTime OrderDate { get; set; }
        public decimal TotalPrice { get; set; }
    }
}

WebAppForWebshop/Models/Orders.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppForWebshop.Models
{
    public class Orders
    {
        [Key]
        public int Id { get; set; }
        public DateTime OrderDate { get; set; }
        
        public  ApplicationUser Customer { get; set; }
    }
}

WebAppForWebshop/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data.Odbc;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Security.Claims;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using WebAppForWebshop.Data;
using WebAppForWebshop.Models;



namespace WebAppForWebshop.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _db;
        private UserManager<ApplicationUser> userManager;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public OrderController(ApplicationDbContext db, UserManager<ApplicationUser> userMrg, IHttpContextAccessor httpContextAccessor)
        {
            this._db = db;
            userManager = userMrg;
            this._httpContextAccessor = httpContextAccessor;
        }
        public IActionResult Index()
        {
            return View();
        }



        public IActionResult Checkout(string _CartId)
        {
            CartAndProduct model = new CartAndProduct();
            model.listForCartAndProduct = (from cart in _db.ShoppingCartItems
                                           join product in _db.Products on cart.ProductId equals product.Id
                                           into Details
                                           from m in Details.DefaultIfEmpty()
                                           select new CartAndProduct
                                           {
                                               CartId = _CartId,
                                               ProductId = m.Id,
                                               ProductName = m.Name,
                                               ProductImage = m.ProductImage,
                                               PricePerItem = m.Price,
                                               Quantity = cart.Quantity,
                                               TotalPrice = m.Price * cart.Quantity,
                                               DateCreated = cart.DateCreated,
                                               ItemId = cart.ItemId
                                           }).ToList();
            return View(model.listForCartAndProduct);
        }

        public void EmptyCart(string _CartId)
        {
            string ShoppingCartId = _CartId;
            var cartItems = _db.ShoppingCartItems.Where(
                c => c.CartId == ShoppingCartId);
            foreach (var cartItem in cartItems)
            {
                _db.ShoppingCartItems.Remove(cartItem);
            }
            // Save changes.             
            _db.SaveChanges();
        }

        public async Task<IActionResult> Receipt(string _CartId)
        {
            string removeCart = _CartId;
            CartAndProduct model = new CartAndProduct();
            // var user = await userManager.FindByIdAsync(User.Identity.GetType());
            var user = await userManager.GetUserAsync(HttpContext.User);
            var user1 = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            model.listForCartAndProduct = (from cart in _db.ShoppingCartItems
                                           join product in _db.Products on cart.ProductId equals product.Id
                                           into Details
                                           from m in Details.DefaultIfEmpty()
                                           select new CartAndProduct
                                           {
                                               CartId = _CartId,
                                               ProductId = m.Id,
                                               ProductName = m.Name,
                                               ProductImage = m.ProductImage,
                                               PricePerItem = m.Price,
                                               Quantity = cart.Quantity,
                                               TotalPrice = m.Price * cart.Quantity,
                                               DateCreated = cart.DateCreated,
                                               ItemId = cart.ItemId
                                           }).ToList();
            var insUser = (ApplicationUser)_db.Users.Where(x => x.Id == user1).FirstOrDefault();

            var order = new Orders()
            {
                OrderDate = DateTime.Now,
                Customer = insUser
            };
            await _db.Orders.AddAsync(order);
            await _db.SaveChangesAsync();
            var orderid = order.Id;
            foreach (var item in model.listForCartAndProduct)
            {
                int count = item.Quantity;
                while (count > 0)
                {
                    count--;
                    var orderref = new OrderReference()
                    {
                        OrderId = order,
                        ProductId = _db.Products.Where(p => p.Id == item.ProductId).FirstOrDefault(),
                        Price = item.PricePerItem
                    };
                    await _db.OrderReferences.AddAsync(orderref);
                }
            }
            EmptyCart(removeCart);
            await _db.SaveChangesAsync();

            return View(model.listForCartAndProduct);
        }

        
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> OrderHistory()
        {
            OrderHistory model = new OrderHistory();
            ApplicationUser tempUser = new ApplicationUser();
            model.listOrderHistory = (from oref in _db.OrderReferences
                                      join order in _db.Orders on oref.OrderId.Id
                                      equals order.Id
                                      join user in _db.Users on order.Customer.Id equals user.Id
                                      into Details
                                      from m in Details.DefaultIfEmpty()
                                      select new OrderHistory
                                      {
                                          OrderId = oref.OrderId.Id,
                                          CustomerId = m.Id,
                                          CustomerUsername = m.UserName,
                                          OrderDate = order.OrderDate,
                                          TotalPrice = oref.Price
                                      }).ToList();

            foreach (var item in model.listOrderHistory)
            {
                var user1 = (ApplicationUser)await _db.Users.Where(x => x.Id == item.CustomerId).FirstOrDefaultAsync();
                item.DeliveryAddress = user1.Address;

            }

            var tempo = new OrderHistory();

            foreach (var item in model.listOrderHistory)
            {
                tempo = new OrderHistory()
                {
                    OrderId = item.OrderId,
                    OrderDate = item.OrderDate,
                    CustomerId = item.CustomerId,
                    CustomerUsername = item.CustomerUsername,
                    DeliveryAddress = item.DeliveryAddress,
                    TotalPrice = item.TotalPrice
                };

                break;

            }

            //var temp = new OrderHistory();
            //var temp = model.listOrderHistory.FirstOrDefault();
            tempo.TotalPrice = tempo.TotalPrice - tempo.TotalPrice;
            foreach (var item in model.listOrderHistory)
            {

                if (tempo.OrderId != item.OrderId)
                {

                    model.finalHistoryList.Add(tempo);
                    tempo = new OrderHistory()
                    {
                        OrderId = item.OrderId,
                        OrderDate = item.OrderDate,
                        CustomerId = item.CustomerId,
                        CustomerUsername = item.CustomerUsername,
                        DeliveryAddress = item.DeliveryAddress,
                        TotalPrice = item.TotalPrice
                    };
                }
                else
                {

                    tempo.TotalPrice = tempo.TotalPrice + item.TotalPrice;
                }

            }
            model.finalHistoryList.Add(tempo);

            return View("OrderHistory", model);
        }

        public async Task<IActionResult> ManageOrder(int id)
        {
            SpecificOrderHistory model = new SpecificOrderHistory();
            model.listSpecificOrderHistory = (from prod in _db.Products
                                              join
                    oref in _db.OrderReferences on prod.Id equals oref.ProductId.Id
                                              join order in _db.Orders on oref.OrderId.Id
                                              equals order.Id
                                              join user in _db.Users on order.Customer.Id equals user.Id
                                              into Details
                                              from m in Details.DefaultIfEmpty()
                                              where oref.OrderId.Id == id
                                              select new SpecificOrderHistory
                                              {
                                                  OrderId = oref.OrderId.Id,
                                                  CustomerId = m.Id,
                                                  CustomerUsername = m.UserName,
                                                  OrderDate = order.OrderDate,

WebAppForWebshop/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebAppForWebshop.Data;
using WebAppForWebshop.Models;



namespace WebAppForWebshop.Controllers
{
    [Authorize]



    public class ShoppingCartController : Controller
    {



        public string ShoppingCartId { get; set; }



        private readonly ApplicationDbContext _db;



        public const string CartSessionKey = "CartId";



        private readonly IHttpContextAccessor _httpContextAccessor;





        public ShoppingCartController(IHttpContextAccessor httpContextAccessor, ApplicationDbContext db)
        {
            this._httpContextAccessor = httpContextAccessor;



            this._db = db;
        }





        //get shopping Cart
        public IActionResult Index()
        {



            ShoppingCartId = GetCartId();
            CartAndProduct model = new CartAndProduct();
            model.listForCartAndProduct = (from cart in _db.ShoppingCartItems
                                           join product in _db.Products on cart.ProductId equals product.Id
                                           into Details
                                           from m in Details.DefaultIfEmpty()
                                           select new CartAndProduct
                                           {
                                               CartId = ShoppingCartId,
                                               ProductId = m.Id,
                                               ProductName = m.Name,
                                               ProductImage = m.ProductImage,
                                               PricePerItem = m.Price,
                                               Quantity = cart.Quantity,
                                               TotalPrice = m.Price * cart.Quantity,
                                               DateCreated = cart.DateCreated,
                                               ItemId = cart.ItemId
                                           }).ToList();

            //return View("Index", _db.ShoppingCartItems.Where(
            //    c => c.CartId == ShoppingCartId).ToList());

            return View("Index", model.listForCartAndProduct);

        }


        public async Task<IActionResult> Delete(string? id)
        {
            var item = await _db.ShoppingCartItems.FindAsync(id);
            _db.ShoppingCartItems.Remove(item);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }



        public IActionResult AddToCart(int id)
        {
            // Retrieve the product from the database. 
            ShoppingCartId = GetCartId();





            var cartItem = _db.ShoppingCartItems.SingleOrDefault(
                c => c.CartId == ShoppingCartId
                && c.ProductId == id);
            if (cartItem == null)
            {
                // Create a new cart item if no cart item exists.                 
                cartItem = new CartItem
                {
                    ItemId = Guid.NewGuid().ToString(),
                    ProductId = id,
                    CartId = ShoppingCartId,
                    Product = _db.Products.SingleOrDefault(
                   p => p.Id == id),
                    Quantity = 1,
                    DateCreated = DateTime.Now
                };





                _db.ShoppingCartItems.Add(cartItem);
            }
            else
            {
                // If the item does exist in the cart,                  
                // then add one to the quantity.                 
                cartItem.Quantity++;
            }
            _db.SaveChanges();



            return RedirectToAction("Index", "Products");
            //return RedirectToAction("Index");
            //return View();
        }



        // deleting all items in the shopping Cart
        public IActionResult EmptyCart()
        {
            ShoppingCartId = GetCartId();
            var cartItems = _db.ShoppingCartItems.Where(
                c => c.CartId == ShoppingCartId);
            foreach (var cartItem in cartItems)
            {
                _db.ShoppingCartItems.Remove(cartItem);
            }
            // Save changes.             
            _db.SaveChanges();
            return RedirectToAction("Index");
        }


        public string GetCartId()
        {





            if (HttpContext.Session.GetString("CartSessionKey") == null)
            {
                if (!string.IsNullOrWhiteSpace(_httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value))
                {
                    HttpContext.Session.SetString("CartSessionKey", _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
                }
                else
                {
                    // Generate a new random GUID using System.Guid class.     
                    Guid tempCartId = Guid.NewGuid();
                    HttpContext.Session.SetString("CartSessionKey", tempCartId.ToString());
                }
            }
            return HttpContext.Session.GetString("CartSessionKey").ToString();
        }


        public IActionResult ChangeAmount(string id, string button)
        {
            var item = _db.ShoppingCartItems.Find(id);
            if (button == "+")
                item.Quantity++;
            else
                item.Quantity--;

            if (item.Quantity < 1)
                _db.ShoppingCartItems.Remove(item);
            else
                _db.Update(item);

            _db.SaveChanges();

            return RedirectToAction("Index");
        }


        public List<CartItem> GetCartItems()
        {
            ShoppingCartId = GetCartId();





            return _db.ShoppingCartItems.Where(
                c => c.CartId == ShoppingCartId).ToList();
        }







    }
}

WebAppForWebshop/Views/Order/Checkout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{ }




@model IEnumerable<WebAppForWebshop.Models.CartAndProduct>




<html lang="en">
<head>





    <title>Group 2 Project</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">





    <title>Group2</title>



    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />


    <link href="~/css/Custom.css" rel="stylesheet" />

    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="~/themes/css/style.css">
    <link rel="stylesheet" href="~/themes/css/bootstrap.min.css">

</head>



<body>





    <div class="container">
        <div class="row">




            <div class="col-sm-2">
                <div>
                    @*<div class="panel-heading">BLACK FRIDAY DEAL</div>
                        <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
                        <div class="panel-footer">Buy 50 mobiles and get a gift card</div>*@
                </div>
            </div>



            <div class="col-sm-8">
                <h2>Checkout</h2>



                @{decimal temp = 0;
        <table class="table" id="customers">
            <thead>
                <tr>
                    @*<th>
                            @Html.DisplayNameFor(model => model.CartId)
                        </th>*@
                    <th>
                        @Html.DisplayNameFor(model => model.ProductId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ProductName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ProductImage)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PricePerItem)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Quantity)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TotalPrice)
                    </th>
                    @*<th>
                            @Html.DisplayNameFor(model => model.DateCreated)
                        </th>*@

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    temp = temp + item.TotalPrice;





    <tr>
        @*<td>
                @Html.DisplayFor(modelItem => item.CartId)
            </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.ProductId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            <img src=" @Html.DisplayFor(modelItem => item.ProductImage)" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PricePerItem)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalPrice)
        </td>
        @*<td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>*@
        @*<td>
            <a asp-action="Edit" asp-route-id="@item.ItemId">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.ItemId">Details</a>
            <a asp-action="Delete" asp-route-id="@item.ItemId">Delete</a>*@
        @*<a asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-id="@item.Id">Add To Cart</a>*@
        @*</td>*@
    </tr>
}





                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>TOTAL PRICE OF ORDER</td>
                    <td>@Math.Round(temp, 2) Kr</td>
                </tr>
            </tbody>
        </table> }






                @foreach (var item in Model)
                {
    @Html.ActionLink("Confirm Purchase", "Receipt", "Order", new { _CartId = item.CartId }, new { @class = "btn-main" })break; @*<button>@Html.ActionLink("Confirm Purchase", "Receipt", "Order", new { item.CartId })</button>break;*@}



                @*@foreach (var item in Model)
                    {
                    @Html.ActionLink("Confirm Purchase", "Receipt", "Order", new { item.CartId }, new { @class = "btn-main" })}*@
                <br />
                <br>
                @Html.ActionLink("Back to Shopping Cart", "Index", "ShoppingCart", new{ @class = "btn-main"})
               @* <button asp-controller="ShoppingCart" asp-action="Index" >Back to Shopping Cart</button>*@


            </div>



            <div class="col-sm-2">
                <div>
                    @*<div class="panel-heading">BLACK FRIDAY DEAL</div>
                        <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
                        <div class="panel-footer">Buy 50 mobiles and get a gift card</div>*@
                </div>
            </div>



        </div>
    </div>
</body>
</html>

WebAppForWebshop/Views/Order/ManageOrder.cshtml
@model WebAppForWebshop.Models.SpecificOrderHistory



<html lang="en">
<head>
    <title>Group 2 Project</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">



    <title>Group2</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />


    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="~/themes/css/style.css">
    <link rel="stylesheet" href="~/themes/css/bootstrap.min.css">


    <link href="~/css/Custom.css" rel="stylesheet" />
</head>
<body>



    <div class="row">
        <div class="col-md-3">
        </div>
        <div class="col-md-6">

            <h2>Management your Order</h2>
            <br />
            <section>

                @if (Model != null)
                {

                    if (Model.listSpecificOrderHistory != null)
                    {<table class="table" id="customers">

                            @foreach (var item in Model.listSpecificOrderHistory)
                            {
                                <tr>
                                    <th>Order</th>
                                    <th>Date</th>
                                    <th>Customer</th>
                                    <th>CustomerID</th>
                                    <th>Delivery Address</th>
                                    <th>Total Price of Order</th>
                                    @if(User.IsInRole("Admin")){<th></th>}
                                </tr>
                                <tr>
                                    <td>@item.OrderId</td>
                                    <td>@item.OrderDate</td>
                                    <td>@item.CustomerUsername</td>
                                    <td>@item.CustomerId</td>
                                    <td>@item.DeliveryAddress</td>
                                    <td>@item.TotalPrice</td>
                                   @if (User.IsInRole("Admin"))
                                   { <td>@Html.ActionLink("DELETE ORDER", "RemoveWholeOrder", "Order", new { orderid = item.OrderId }, new { @class = "btn btn-danger" })</td>}
                                </tr>
                                break;
                            }


                            @foreach (var item in Model.listSpecificOrderHistory)
                            {

                                <tr> <td><img src="@item.ProductImage" /></td> <td>@item.ProductId</td>   <td>@item.ProductName </td> <td>@item.PricePerItem Kr</td>  <td></td> <td></td> @if (User.IsInRole("Admin"))
                                {<td>@Html.ActionLink("DELETE  ITEM", "RemoveProductFromOrder", "Order", new { orefid = item.orefId, orderid = item.OrderId }, new { @class = "btn btn-danger" })   </td>}     </tr>

                            }
                        </table>
                    }
                }
            </section>


        </div>
        <div class="col-md-3">
        </div>

    </div>


    @section Scripts {
        <partial name="_ValidationScriptsPartial" />
    }
</body>
</html>

WebAppForWebshop/Views/Order/OrderHistory.cshtml
@model WebAppForWebshop.Models.OrderHistory



<html lang="en">
<head>
    <title>Group 2 Project</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">



    <title>Group2</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />


    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="~/themes/css/style.css">
    <link rel="stylesheet" href="~/themes/css/bootstrap.min.css">


    <link href="~/css/Custom.css" rel="stylesheet" />
</head>
<body>



    <div class="row">
        <div class="col-md-3">
        </div>
        <div class="col-md-6">
            <h2>Order History</h2>
            <br />
            <section>
                <div>

                    @if (Model != null)
                    {
                        if (Model.finalHistoryList != null)
                        {


                            <table class="table" id="customers">
                                <tr><th>Order</th><th>Date</th><th>Customer</th><th>Username</th><th>Delivery address</th><th>Total Price</th><th>Click</th></tr>
                                @foreach (var item in Model.finalHistoryList)
                                {

                                    <tr>
                                        <td>@item.OrderId</td>
                                        <td>@item.OrderDate</td>
                                        <td>@item.CustomerId</td>
                                        <td>@item.CustomerUsername</td>
                                        <td>@item.DeliveryAddress</td>
                                        <td>@item.TotalPrice</td>
                                        <td>@Html.ActionLink("MANAGE", "ManageOrder", "Order", new { id = item.OrderId }, new { @class = "btn-main" })</td>
                                    </tr>


                                }

                            </table>

                        }
                    }
                </div>

                <br />


               @* <div>@Html.ActionLink("SHOPPING HISTORY", "ShoppingHistory", "Order", new { @class = "btn-main" })</div>*@
            
            </section>


        </div>
        <div class="col-md-3">
        </div>

    </div>


    @section Scripts {
        <partial name="_ValidationScriptsPartial" />
    }
</body>
</html>